import { Amplify } from 'aws-amplify';
import { generateClient } from 'aws-amplify/data';
import type { Schema } from '../../amplify/data/resource';
import outputs from '../../amplify_outputs.json';

/**
 * Amplify configuration.
 *
 * `amplify_outputs.json` is generated by the backend deployment — `npx ampx
 * sandbox` locally, `npx ampx pipeline-deploy` in the Amplify build — and is
 * gitignored. See `amplify_outputs.example.json` if you need a placeholder to
 * compile against.
 */
Amplify.configure(outputs);

/**
 * Two clients, because the application serves two kinds of visitor.
 *
 * A signed-in player calls with `userPool`, so the Lambda sees their Cognito
 * claims and can identify them. A visitor who is not signed in calls with
 * `identityPool` as a guest, which resolves to an anonymous viewer server-side
 * and gets the redacted public view.
 *
 * The distinction is a convenience for choosing the right credentials — it is
 * not a security boundary. The backend decides what each identity may see, and
 * an authenticated user calling as a guest simply gets less, not more.
 */
export const authedClient = generateClient<Schema>({ authMode: 'userPool' });
export const guestClient = generateClient<Schema>({ authMode: 'identityPool' });

export function clientFor(signedIn: boolean) {
  return signedIn ? authedClient : guestClient;
}
