import { Amplify } from 'aws-amplify';

// Only try to import aws-exports if it exists (handled by try-catch)
try {
  // @ts-ignore - This file is auto-generated by Amplify CLI
  const awsExports = require('./aws-exports').default;
  Amplify.configure(awsExports);
} catch (error) {
  console.warn('Could not load aws-exports.js. Running without Amplify configuration.');
  
  // Configure with minimal config to prevent errors
  Amplify.configure({
    Auth: {
      Cognito: {
        userPoolId: '',
        userPoolClientId: ''
      }
    }
  });
}
